/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as AgentsAgentIdRouteImport } from './routes/agents/$agentId'
import { Route as AgentsNewRouteImport } from './routes/agents/new'
import { Route as EvaluationsIndexRouteImport } from './routes/evaluations/index'
import { Route as EvaluationsEvaluationIdIndexRouteImport } from './routes/evaluations/$evaluationId/index'
import { Route as EvaluationsEvaluationIdRunningRouteImport } from './routes/evaluations/$evaluationId/running'
import { Route as EvaluationsEvaluationIdTestsTestIdRouteImport } from './routes/evaluations/$evaluationId/tests/$testId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsNewRoute = AgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationsIndexRoute = EvaluationsIndexRouteImport.update({
  id: '/evaluations/',
  path: '/evaluations/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationsEvaluationIdIndexRoute =
  EvaluationsEvaluationIdIndexRouteImport.update({
    id: '/evaluations/$evaluationId/',
    path: '/evaluations/$evaluationId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const EvaluationsEvaluationIdRunningRoute =
  EvaluationsEvaluationIdRunningRouteImport.update({
    id: '/evaluations/$evaluationId/running',
    path: '/evaluations/$evaluationId/running',
    getParentRoute: () => rootRouteImport,
  } as any)
const EvaluationsEvaluationIdTestsTestIdRoute =
  EvaluationsEvaluationIdTestsTestIdRouteImport.update({
    id: '/evaluations/$evaluationId/tests/$testId',
    path: '/evaluations/$evaluationId/tests/$testId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/agents/new': typeof AgentsNewRoute
  '/agents/': typeof AgentsIndexRoute
  '/evaluations/': typeof EvaluationsIndexRoute
  '/evaluations/$evaluationId/running': typeof EvaluationsEvaluationIdRunningRoute
  '/evaluations/$evaluationId/': typeof EvaluationsEvaluationIdIndexRoute
  '/evaluations/$evaluationId/tests/$testId': typeof EvaluationsEvaluationIdTestsTestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/agents/new': typeof AgentsNewRoute
  '/agents': typeof AgentsIndexRoute
  '/evaluations': typeof EvaluationsIndexRoute
  '/evaluations/$evaluationId/running': typeof EvaluationsEvaluationIdRunningRoute
  '/evaluations/$evaluationId': typeof EvaluationsEvaluationIdIndexRoute
  '/evaluations/$evaluationId/tests/$testId': typeof EvaluationsEvaluationIdTestsTestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/agents/new': typeof AgentsNewRoute
  '/agents/': typeof AgentsIndexRoute
  '/evaluations/': typeof EvaluationsIndexRoute
  '/evaluations/$evaluationId/running': typeof EvaluationsEvaluationIdRunningRoute
  '/evaluations/$evaluationId/': typeof EvaluationsEvaluationIdIndexRoute
  '/evaluations/$evaluationId/tests/$testId': typeof EvaluationsEvaluationIdTestsTestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/dashboard'
    | '/reports'
    | '/settings'
    | '/agents/$agentId'
    | '/agents/new'
    | '/agents/'
    | '/evaluations/'
    | '/evaluations/$evaluationId/running'
    | '/evaluations/$evaluationId/'
    | '/evaluations/$evaluationId/tests/$testId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/dashboard'
    | '/reports'
    | '/settings'
    | '/agents/$agentId'
    | '/agents/new'
    | '/agents'
    | '/evaluations'
    | '/evaluations/$evaluationId/running'
    | '/evaluations/$evaluationId'
    | '/evaluations/$evaluationId/tests/$testId'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/dashboard'
    | '/reports'
    | '/settings'
    | '/agents/$agentId'
    | '/agents/new'
    | '/agents/'
    | '/evaluations/'
    | '/evaluations/$evaluationId/running'
    | '/evaluations/$evaluationId/'
    | '/evaluations/$evaluationId/tests/$testId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  DashboardRoute: typeof DashboardRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
  AgentsNewRoute: typeof AgentsNewRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  EvaluationsIndexRoute: typeof EvaluationsIndexRoute
  EvaluationsEvaluationIdRunningRoute: typeof EvaluationsEvaluationIdRunningRoute
  EvaluationsEvaluationIdIndexRoute: typeof EvaluationsEvaluationIdIndexRoute
  EvaluationsEvaluationIdTestsTestIdRoute: typeof EvaluationsEvaluationIdTestsTestIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/new': {
      id: '/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AgentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluations/': {
      id: '/evaluations/'
      path: '/evaluations'
      fullPath: '/evaluations/'
      preLoaderRoute: typeof EvaluationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluations/$evaluationId/': {
      id: '/evaluations/$evaluationId/'
      path: '/evaluations/$evaluationId'
      fullPath: '/evaluations/$evaluationId/'
      preLoaderRoute: typeof EvaluationsEvaluationIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluations/$evaluationId/running': {
      id: '/evaluations/$evaluationId/running'
      path: '/evaluations/$evaluationId/running'
      fullPath: '/evaluations/$evaluationId/running'
      preLoaderRoute: typeof EvaluationsEvaluationIdRunningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluations/$evaluationId/tests/$testId': {
      id: '/evaluations/$evaluationId/tests/$testId'
      path: '/evaluations/$evaluationId/tests/$testId'
      fullPath: '/evaluations/$evaluationId/tests/$testId'
      preLoaderRoute: typeof EvaluationsEvaluationIdTestsTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  DashboardRoute: DashboardRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  AgentsAgentIdRoute: AgentsAgentIdRoute,
  AgentsNewRoute: AgentsNewRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  EvaluationsIndexRoute: EvaluationsIndexRoute,
  EvaluationsEvaluationIdRunningRoute: EvaluationsEvaluationIdRunningRoute,
  EvaluationsEvaluationIdIndexRoute: EvaluationsEvaluationIdIndexRoute,
  EvaluationsEvaluationIdTestsTestIdRoute:
    EvaluationsEvaluationIdTestsTestIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
